# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-02-21 12:10:56
"""
import arcpy

def Flooding():  # Flooding Analysis

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    floodzones = "floodzones"
    basin = "basin"

    # Process: Clip (Clip) (analysis)
    Floodzones_Clip = "C:\\Users\\acbaum1\\OneDrive - IL State University\\GEO 325\\Week 5\\Lab5_PyWindow_Geoprocessing\\Py_Ex03\\data\\Floodzones_Clip.shp"
    arcpy.analysis.Clip(in_features=floodzones, clip_features=basin, out_feature_class=Floodzones_Clip, cluster_tolerance="")

    # Process: Select (Select) (analysis)
    Flooding = "C:\\Users\\acbaum1\\OneDrive - IL State University\\GEO 325\\Week 5\\Lab5_PyWindow_Geoprocessing\\Py_Ex03\\data\\Study.gdb\\Flooding"
    arcpy.analysis.Select(in_features=Floodzones_Clip, out_feature_class=Flooding, where_clause="SFHA = 'IN'")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\acbaum1\OneDrive - IL State University\GEO 325\Week 5\Lab5_PyWindow_Geoprocessing\Py_Ex03\data\Study.gdb", workspace=r"C:\Users\acbaum1\OneDrive - IL State University\GEO 325\Week 5\Lab5_PyWindow_Geoprocessing\Py_Ex03\data\Study.gdb"):
        Flooding()
